### ISSUE TITLE
CSGO timescale fix

### ISSUE THREAD

**Issue by e-slut** [TotallyMehis/Influx-Timer#37] opened 2017-07-14 14:56 UTC
I talked to blacky and he said he doesn't use host_timescale he also mentioned something about stamina. He did say he showed it in one of his videos I think it was this video https://www.youtube.com/watch?v=8V6kg2_2Xgw

Also saw this in his comments
"m_flLaggedMovementValue recreates timescale pretty much because it runs frametime = frametime*m_flLaggedMovementValue before any players move funcs are called the only thing is this doesn't apply to the server like timescale so you have to use the value of it to give the player their time and mess with the replay bot as well xd﻿"

**Comment by TotallyMehis** [comment] 2017-07-15 12:22
You reminded me to test differences between timescales and found out that; host_timescale works perfectly in CSS, no inconsistencies between scales. CS:GO has inconsistencies, so I attempted to use laggedmovementvalue but it has similar inconsistencies even when you try to throttle usercmds.

Auto-strafe, No stamina, Value is XY speed:

(**100tick**)
**CSS - Six jumps without timescale**: 630 (447 frames)
**CSS - Six jumps with host_timescale 0.3**: 630 (447 frames)
**CSS - Six jumps with laggedmovementvalue 0.3 (no throttle)**: 1160.344 (1502 frames)
**CSS - Six jumps with laggedmovementvalue 0.3 (throttle)**: 626.418 (1502 frames)

(**128tick**)
**CS:GO - Six jumps without timescale**: 714.982 (574 frames)
**CS:GO - Six jumps with host_timescale 0.3**: 695.844 (574 frames)
**CS:GO - Six jumps with laggedmovementvalue 0.3 (no throttle)**: 1313.848 (1924 frames)
**CS:GO - Six jumps with laggedmovementvalue 0.3 (throttle)**: 751.797 (1924 frames)

No throttling: Simply changing laggedmovementvalue and not changing anything else.
Throttling: Using last processed usercmd when ignoring current usercmd. (process every (1 / timescale) frames)


I'm fairly certain the reason why CS:GO is different is because of some server/client command that is different compared to CSS. This would make the fix a lot simpler. Regarding the lagginess of CS:GO timescale; fixing the cause of these inconsistencies will probably fix it as well.

Conclusion, fuck TAS and fuck CS:GO.

**Comment by TotallyMehis** [comment] 2017-07-15 19:56
No need to close this issue. It needs to be worked on.

**Comment by e-slut** [comment] 2017-07-16 01:49
Couldn't you slow down the autostrafer? or maybe disable it in timescale if it's that big of a problem. I know it's possible KZendo did it

**Comment by shavitush** [comment] 2017-07-31 10:55
> I'm fairly certain the reason why CS:GO is different is because of some server/client command that is different compared to CSS.

It's more about the way CS:GO does usercmds, and that's why you can use `fps_max 128` to break strafe gains and get much more. Try strafing in CS:GO with 60 FPS and then with over 128.. your 60 FPS will be horrible. That issue doesn't exist in CS:S since about a year ago, hence why fps_max scrolling is not really good nowadays.

I've noticed that the CS:GO SRCDS also "receives" (more like spoofs) usercmds from clients when they aren't sending them. I think it's Valve's way to fight "psilent" cheats and I also am certain that this is why your CS:GO TAS is problematic while throttling.

**Closed as completed** 2020-03-23 11:59 UTC
Labels: question
